services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    command: >
      sh -c "cp .env.example .env && npm run dev -- --host"
    ports:
      - 5173:5173
