services:
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    volumes:
      - ./:/app:cached
      - /app/vendor
    command: >
      sh -c "
        php artisan serve --host 0.0.0.0
      "
    ports:
      - 8000:8000
