services:
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    volumes:
      - ./:/app:cached
      - /app/vendor
    command: >
      sh -c "
        composer dump-autoload --ignore-platform-reqs && \
        cp .env.example .env && \
        php artisan serve --host 0.0.0.0
      "
    ports:
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    command: >
      sh -c "cp .env.example .env && npm run dev -- --host"
    ports:
      - 5173:5173
